version: '3'
services:
  mysql:
    # restart: always
    image: mysql:5.7
    container_name: my_mysql
    volumes:
      - ./data:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
      #      数据库还原目录 可将需要还原的sql文件放在这里
    environment:
      - "MYSQL_ROOT_PASSWORD=Fsh_2021"
      - "MYSQL_DATABASE=airflow"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306
